FROM docker.io/library/python:3.14-alpine3.23@sha256:dd4d2bd5b53d9b25a51da13addf2be586beebd5387e289e798e4083d94ca837a

WORKDIR /app
COPY pyproject.toml .
COPY requirements.lock .
COPY ui/ ui/

RUN python -m pip install --no-cache-dir --upgrade pip==26.0.1 && \
    python -m pip install --no-cache-dir --require-hashes -r requirements.lock && \
    python -m pip install --no-cache-dir --no-deps .

USER 65534:65534
EXPOSE 8480
ENTRYPOINT ["secure-ai-ui"]
