FROM docker.io/library/python:3.14-alpine3.23@sha256:dd4d2bd5b53d9b25a51da13addf2be586beebd5387e289e798e4083d94ca837a

WORKDIR /app
COPY requirements.txt .
COPY setup.py .
COPY agent/ agent/

RUN python -m pip install --no-cache-dir --upgrade pip==26.0.1 && \
    python -m pip install --no-cache-dir -r requirements.txt && \
    python -m pip install --no-cache-dir .

USER 65534:65534
EXPOSE 8476
ENTRYPOINT ["secai-agent"]
